export const BANK_SELECT = 'BANK_SELECT';
export const STARTED_BUTTON_CLICK = 'STARTED_BUTTON_CLICK';
export const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS';

export const TRANSACTIONS_REQUEST = 'CONTACTS_REQUEST';
export const TRANSACTIONS_SUCCESS = 'CONTACTS_SUCCESS';
export const TRANSACTIONS_FAILURE = 'CONTACTS_FAILURE';
